version: "3.4"
services:
  golang:
    tty: true
    image: golang:1.19
    volumes:
      - .:/app/src/service/api
    working_dir: /app/src/service/api
    env_file:
      - .env
    command: bash -c "go install github.com/cosmtrek/air@latest && air -c
      /app/src/service/api/air.toml ."
    expose:
      - "${API_PORT}"
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database
    links:
      - database

  database:
    image: "postgres:13"
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}

volumes:
  data:

