version: "3.3"
services:
  golang:
    tty: true
    image: golang:1.16
    volumes:
      - .:/go/src/service/api
    working_dir: /go/src/service/api
    env_file:
      - .env
    command: bash -c "go get -u github.com/cosmtrek/air && air -c /go/src/service/api/air.toml ."
    expose:
      - "${API_PORT}"
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - database
    links:
      - database
    network_mode: bridge

  database:
    image: "postgres:13"
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    environment:
      TZ: ${API_TZ}
      LC_ALL: C.UTF-8
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    command: -p ${POSTGRES_PORT}
    network_mode: bridge

volumes:
  data:
