// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	Price     float64   `json:"price"`
	Name      string    `json:"name"`
}

type User struct {
	ID        uuid.UUID    `json:"id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Lastname  string       `json:"lastname"`
	Firstname string       `json:"firstname"`
}
