// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (price, name)
VALUES ($1, $2) RETURNING id, created_at, price, name
`

type CreateBookParams struct {
	Price float64 `json:"price"`
	Name  string  `json:"name"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.queryRow(ctx, q.createBookStmt, createBook, arg.Price, arg.Name)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Price,
		&i.Name,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteBookStmt, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, created_at, price, name FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.queryRow(ctx, q.getBookStmt, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Price,
		&i.Name,
	)
	return i, err
}

const getBooks = `-- name: GetBooks :many
SELECT id, created_at, price, name FROM books
`

func (q *Queries) GetBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.query(ctx, q.getBooksStmt, getBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Price,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
